tdenginewriter rebuiled
taosdata/DataX pull request #20
Opened 2022-02-14 10:59 UTC by zyyang-taosdata

tdenginewriter rebuiled

2022-02-18 06:26 UTC, huolibo commented on tdenginewriter/pom.xml
> +            <version>1.2.58</version>
the latest fastjson version is 1.2.79

2022-02-18 08:10 UTC, dingbo8128 requested changes
tdenginewrite.md and tdenginewrite-CN.md should be updated

2022-02-18 10:33 UTC, huolibo approved these changes
LGTM

2022-02-20 08:50 UTC, zyyang-taosdata commented
> tdenginewrite.md and tdenginewrite-CN.md should be updated

2022-02-20 08:51 UTC, zyyang-taosdata commented
> tdenginewrite.md and tdenginewrite-CN.md should be updated

docs updated

2022-02-21 08:26 UTC, dingbo8128 approved these changes

2022-02-21 08:27 UTC, sangshuduo approved these changes

2022-02-21 08:27 UTC, merged